services:

  web01:
    build:
      context: ./docker
    container_name: ansible-web01
    hostname: web01
    ports:
      - "2221:22"
      - "5001:5000"

  web02:
    build:
      context: ./docker
    container_name: ansible-web02
    hostname: web02
    ports:
      - "2222:22"

  db01:
    build:
      context: ./docker
    container_name: ansible-db01
    hostname: db01
    ports:
      - "2223:22"

  lb01:
    build:
      context: ./docker
    container_name: ansible-lb01
    hostname: lb01
    ports:
      - "2224:22"
      - "8080:80"

  prometheus:
    image: prom/prometheus:latest
    container_name: ansible-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:latest
    container_name: ansible-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
