[web]
web01 ansible_host=127.0.0.1 ansible_port=2221
web02 ansible_host=127.0.0.1 ansible_port=2222

[web:vars]
ansible_user=ansible

[database]
db01 ansible_host=127.0.0.1 ansible_port=2223

[database:vars]
ansible_user=ansible

[loadbalancer]
lb01 ansible_host=127.0.0.1 ansible_port=2224 ansible_user=ansible
