---
- name: Verify HAProxy configuration
  ansible.builtin.command:
    cmd: haproxy -c -f /etc/haproxy/haproxy.cfg
  register: haproxy_config_check
  changed_when: false
  become: true

- name: Verify HAProxy is listening on port 80
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: 80
    state: started
    timeout: 10
  become: true
