---
- name: Reload Supervisor configuration
  ansible.builtin.shell: |
    supervisorctl reread
    supervisorctl update
  become: true

- name: Restart application
  ansible.builtin.command:
    cmd: supervisorctl restart myapp
  become: true
