---
- name: Install node exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present
    update_cache: true
  become: true

- name: Ensure node exporter is running
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: true
  become: true
