name: Ansible CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Ansible
        run: |
          python3 -m venv .venv
          .venv/bin/pip install ansible

      - name: Install Ansible collections
        run: |
          .venv/bin/ansible-galaxy collection install -r requirements.yml

      - name: Deploy infrastructure
        run: |
          .venv/bin/ansible-playbook playbooks/site.yml \
            --private-key ~/.ssh/ansible_lab_cd
